sudo: required
dist: trusty
language: elixir

elixir:
  - 1.6.4
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 10
script:
  - mix credo
  - mix test
